### PR TITLE
Fixing test_config test.

### PR DESCRIPTION
**Pull request by krmahadevan**

### CODE REVIEW

**Comment by subhagho** [comment]
What was the reason for changing the string * to string?

**Comment by krmahadevan** [comment]
I was seeing some malloc errors. Since I wasn't able to figure out where it was coming from (it was just a guess that it perhaps is coming from the `Path` class), I was searching around on the net and found that when it comes to working with `string` we shouldn't resort to using the `new` operator because it kind of defeats all the goodies that the `string` class brings in (I am yet to figure out what those are). So i changed the `Path` class to work with regular string instead of a string pointer.

The exception that I was seeing was something like this `malloc: *** error for object: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug`

**Comment by subhagho** [comment]
Ok. The main advantage of not using a string ptr is memory co-location, especially when dealing with stack objects. It makes sense not to have unnecessary pointer references, but there is also the reverse problem of the stack getting too heavy. 

The pointer free thing is actually a MacOS only problem. Works fine on linux, but was planning on debugging it further on the Mac. Put if the move to string local solves the problem that's fine.

One tool you might want to start getting familiar with is valagrind. It's a memory analysis tool for C/C++, will use it to detect leaks.

**Comment by krmahadevan** [comment]
Thanks sirji.. I did read about that `valagrind` tool. Will spend sometime getting familiar with it as well.

**Pull request merged**
