### PR TITLE
Test case enhancements

### PR DESCRIPTION
**Pull request by krmahadevan**
* Adding boost library for easing test case 
execution (test cases need absolute path of logger
config which can now be provided via boost.
* Enhanced tests for test_alarm.

### CODE REVIEW

**Comment by krmahadevan** [comment]
ping @subhagho

**Comment by subhagho** [comment]
What is boost being used for?

I generally try to avoid using boost as it is a very heavy library. But if it is only for test cases I am fine.

**Comment by krmahadevan** [comment]
I have here used boost only for the test cases. I found it as an option to get the absolute file path from a relative file path and started to use it to point to the logger configuration for the tests. I am not yet there to touch main code :) Just fiddling around with the tests alone.

**Comment by subhagho** [comment]
BTW, if you just need absolute path, you can use file_utils::canonical_path().

**Pull request merged**
